version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lab2_postgres
    environment:
      POSTGRES_USER: simpleuser # Очень простое имя пользователя
      POSTGRES_PASSWORD: 12345 # Очень простой пароль
      POSTGRES_DB: lung_db # Название базы данных
    ports:
      - '5432:5432' # Слушаем на стандартном порту
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: lab2_adminer
    ports:
      - '8081:8080' # Заходим на localhost:8081
    depends_on:
      - postgres

volumes:
  postgres_data:
