version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lung_capacity_db
    environment:
      POSTGRES_DB: lung_capacity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5 # Меняем на md5 вместо trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'password_encryption=md5' # Форсируем md5

  adminer:
    image: adminer
    container_name: adminer_lung
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
